#include <metal/metal.hpp>
#include <metal/postgres_execution.hpp>

#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <memory>
#include <optional>
#include <string>

namespace {

struct [[=metal::mapping::table{"pg_live_records"}]] PgLiveRecord {
    [[=metal::mapping::primary_key, =metal::mapping::generated]]
    std::int64_t id{};
    std::string name;
    bool active{};
    double score{};
    metal::Blob payload;
    std::optional<std::string> note;
};

static_assert(metal::reflect::validate_mapping<PgLiveRecord>());

const metal::DatabaseTable& table_named(
    const metal::DatabaseSchema& schema,
    const std::string& name) {
    const auto found = std::find_if(
        schema.tables.begin(), schema.tables.end(),
        [&](const metal::DatabaseTable& table) { return table.name == name; });
    assert(found != schema.tables.end());
    return *found;
}

const metal::DatabaseColumn& column_named(
    const metal::DatabaseTable& table,
    const std::string& name) {
    const auto found = std::find_if(
        table.columns.begin(), table.columns.end(),
        [&](const metal::DatabaseColumn& column) { return column.name == name; });
    assert(found != table.columns.end());
    return *found;
}

std::int64_t count_named(metal::PostgresExecutor& executor, const std::string& name) {
    const auto result = executor.execute(
        "SELECT COUNT(*)::BIGINT AS total FROM pg_live_records WHERE name = $1;",
        {name});
    assert(result.rows.size() == 1);
    return metal::from_value<std::int64_t>(result.rows.front().at("total"));
}

void test_live_postgres(const std::string& connection_string) {
    auto executor = std::make_shared<metal::PostgresExecutor>(connection_string);
    auto dialect = std::make_shared<metal::PostgresDialect>();

    executor->execute("DROP SCHEMA IF EXISTS metalorm_e2e CASCADE;");
    executor->execute("CREATE SCHEMA metalorm_e2e;");
    executor->execute("SET search_path TO metalorm_e2e;");

    const metal::Blob payload{
        std::byte{0x00}, std::byte{0xff}, std::byte{0x41}, std::byte{0x00}};

    const auto transport = executor->execute(
        "SELECT $1::BIGINT AS i, $2::DOUBLE PRECISION AS d, $3::TEXT AS s, "
        "$4::BOOLEAN AS b, $5::BYTEA AS bytes, $6::TEXT AS n;",
        {
            std::int64_t{42},
            3.5,
            std::string{"hello"},
            true,
            payload,
            nullptr
        });
    assert(transport.rows.size() == 1);
    const auto& transport_row = transport.rows.front();
    assert(metal::from_value<std::int64_t>(transport_row.at("i")) == 42);
    assert(metal::from_value<double>(transport_row.at("d")) == 3.5);
    assert(metal::from_value<std::string>(transport_row.at("s")) == "hello");
    assert(metal::from_value<bool>(transport_row.at("b")));
    assert(metal::from_value<metal::Blob>(transport_row.at("bytes")) == payload);
    assert(std::holds_alternative<std::nullptr_t>(transport_row.at("n")));

    const auto ddl = metal::create_table_sql<PgLiveRecord>(*dialect);
    assert(ddl.find("GENERATED BY DEFAULT AS IDENTITY") != std::string::npos);
    assert(ddl.find("BOOLEAN") != std::string::npos);
    assert(ddl.find("DOUBLE PRECISION") != std::string::npos);
    assert(ddl.find("BYTEA") != std::string::npos);
    executor->execute(ddl);
    executor->execute(
        "CREATE UNIQUE INDEX pg_live_records_name_uq ON pg_live_records(name);");

    metal::Session session{executor, dialect};

    executor->execute(
        "CREATE PROCEDURE metalorm_e2e.bump_state("
        "IN input BIGINT, OUT total BIGINT, INOUT state TEXT) "
        "LANGUAGE plpgsql AS $$ BEGIN total := input * 2; state := state || '-done'; END $$;");
    const auto procedure = metal::call_procedure("bump_state", std::string{"metalorm_e2e"})
        .in("input", std::int64_t{21})
        .out("total", std::string{"BIGINT"})
        .in_out("state", std::string{"ready"}, std::string{"TEXT"});
    const auto procedure_result = procedure.execute(session);
    assert(procedure_result.result_sets.size() == 1);
    assert(metal::from_value<std::int64_t>(procedure_result.out.at("total")) == 42);
    assert(metal::from_value<std::string>(procedure_result.out.at("state")) == "ready-done");

    auto record = std::make_shared<PgLiveRecord>();
    record->name = "alpha";
    record->active = true;
    record->score = 7.25;
    record->payload = payload;
    record->note = std::string{"present"};
    session.persist(record);
    session.commit();
    assert(record->id > 0);
    const auto alpha_id = record->id;

    session.clear();
    const auto loaded = session.find<PgLiveRecord>(alpha_id);
    assert(loaded);
    assert(loaded->name == "alpha");
    assert(loaded->active);
    assert(loaded->score == 7.25);
    assert(loaded->payload == payload);
    assert(loaded->note == std::optional<std::string>{"present"});

    const auto upsert = metal::InsertQueryBuilder{"pg_live_records"}
        .values({
            {"name", std::string{"alpha"}},
            {"active", true},
            {"score", 9.5},
            {"payload", payload},
            {"note", std::string{"updated"}}
        })
        .on_conflict({"name"})
        .do_update({
            {"score", metal::excluded("score")},
            {"note", metal::excluded("note")}
        })
        .returning({"id", "score", "note"})
        .compile(*dialect);
    const auto upserted = executor->execute(upsert.sql, upsert.params);
    assert(upserted.rows.size() == 1);
    assert(metal::from_value<std::int64_t>(upserted.rows.front().at("id")) == alpha_id);
    assert(metal::from_value<double>(upserted.rows.front().at("score")) == 9.5);
    assert(metal::from_value<std::string>(upserted.rows.front().at("note")) == "updated");

    executor->begin_transaction();
    executor->execute(
        "INSERT INTO pg_live_records(name, active, score, payload, note) "
        "VALUES ($1, $2, $3, $4, $5);",
        {std::string{"tx-keep"}, true, 1.0, payload, nullptr});
    executor->savepoint("live_sp");
    executor->execute(
        "INSERT INTO pg_live_records(name, active, score, payload, note) "
        "VALUES ($1, $2, $3, $4, $5);",
        {std::string{"tx-discard"}, false, 2.0, payload, nullptr});
    executor->rollback_to_savepoint("live_sp");
    executor->release_savepoint("live_sp");
    executor->commit_transaction();
    assert(count_named(*executor, "tx-keep") == 1);
    assert(count_named(*executor, "tx-discard") == 0);

    executor->begin_transaction();
    executor->execute(
        "INSERT INTO pg_live_records(name, active, score, payload, note) "
        "VALUES ($1, $2, $3, $4, $5);",
        {std::string{"tx-rollback"}, true, 3.0, payload, nullptr});
    executor->rollback_transaction();
    assert(count_named(*executor, "tx-rollback") == 0);

    const auto schema = metal::introspect_postgres(
        *executor,
        metal::IntrospectOptions{
            .schema = std::string{"metalorm_e2e"},
            .include_tables = {"pg_live_records"},
            .include_views = false
        });
    assert(schema.tables.size() == 1);
    const auto& table = table_named(schema, "pg_live_records");
    assert(table.primary_key == std::vector<std::string>{"id"});
    const auto& id = column_named(table, "id");
    const auto& active = column_named(table, "active");
    const auto& score = column_named(table, "score");
    const auto& bytes = column_named(table, "payload");
    const auto& note = column_named(table, "note");
    assert(id.type == "bigint");
    assert(id.auto_increment);
    assert(active.type == "boolean");
    assert(score.type == "double precision");
    assert(bytes.type == "bytea");
    assert(note.type == "text");
    assert(!note.not_null);

    executor->execute("DROP SCHEMA metalorm_e2e CASCADE;");
}

} // namespace

int main() {
    const char* connection_string = std::getenv("METAL_ORM_POSTGRES_E2E_URL");
    if (!connection_string || !*connection_string) return 0;
    test_live_postgres(connection_string);
}
