#pragma once

#include "metal/collection.hpp"
#include "metal/ddl.hpp"
#include "metal/dml.hpp"
#include "metal/execution.hpp"
#include "metal/identity_map.hpp"
#include "metal/mapping.hpp"
#include "metal/polymorphic.hpp"
#include "metal/orm.hpp"
#include "metal/query.hpp"
#include "metal/reflection.hpp"
#include "metal/relation_change_processor.hpp"
#include "metal/runtime_pagination.hpp"
#include "metal/runtime_types.hpp"
#include "metal/unit_of_work.hpp"
#include "metal/value.hpp"
#include "metal/version.hpp"
